# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: check-added-large-files
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements
      - id: file-contents-sorter
        files: .gitignore

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8

  - repo: https://github.com/timothycrosley/isort
    rev: 5.12.0
    hooks:
      - id: isort

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        exclude: templates

  - repo: https://github.com/rtts/djhtml
    rev: "v2.0.0"
    hooks:
      - id: djhtml
  - repo: https://github.com/Riverside-Healthcare/djLint
    rev: v1.33.0
    hooks:
      - id: djlint-reformat-django
      - id: djlint-django
