name: update_task_definition

# Were we can define the inputs that our action will accept
inputs:
  service:
    description: The name of the service
    required: true
  container:
    description: The name of the container inside the task definition needing patched
    required: true
  environment:
    description: The environment being targeted
    required: true
  image_id:
    description: The updated image
    required: true

description: Updates a task definition with new image name and deploys it

runs:
  using: "composite"
  steps:
  # aws-ecs/deploy-service-update
  - name: Download task definition
    shell: bash
    env:
      UPDATED_TASK_NAME: "${{ inputs.environment }}-${{ inputs.service }}-task-definition.json"
    run: |
      aws ecs describe-task-definition --include TAGS --task-definition bodds_${{ inputs.service }}_${{ inputs.environment }} | jq '.taskDefinition["containerDefinitions"][] |= if (.name=="${{ inputs.container }}" ) then (.image = "${{ inputs.image_id }}") else . end' > $UPDATED_TASK_NAME
      cat $UPDATED_TASK_NAME

  - name: Deploy Amazon ECS task definition
    uses: aws-actions/amazon-ecs-deploy-task-definition@v1
    with:
      task-definition: "${{ inputs.environment }}-${{ inputs.service }}-task-definition.json"
      service: ${{ inputs.service }}
      cluster: bodds-${{ inputs.environment }}
      wait-for-service-stability: true
