name: update_task_definition

# Were we can define the inputs that our action will accept
inputs:
  service:
    description: The name of the service
    required: true
  container:
    description: The name of the container inside the task definition needing patched
    required: true
  environment:
    description: The environment being targeted
    required: true
  image_id:
    description: The updated image
    required: true

description: Updates a task definition with new image name and deploys it

runs:
  using: "composite"
  steps:
  # aws-ecs/deploy-service-update
    - name: Download task definition
      shell: bash
      env:
        TASK_FAMILY: bodds_${{ inputs.service }}_${{ inputs.environment }}
        IMAGE: ${{ inputs.image_id }}
        CONTAINER: ${{ inputs.container }}
        CLUSTER: bodds-${{ inputs.environment }}
        SERVICE: ${{ inputs.service }}
      run: |
        aws ecs describe-task-definition --include TAGS --task-definition $TASK_FAMILY | jq '.taskDefinition.containerDefinitions[] |= if (.name=="$CONTAINER" ) then (.image = $IMAGE) else . end | .taskDefinition["tags"] = .tags | .taskDefinition | del(.taskDefinitionArn) | del(.revision) | del(.status) | del(.requiresAttributes) | del(.compatabilities) | del(.registeredAt) | del(.registeredBy) | del(.compatibilities)' > ${{ github.workspace }}/task-definition.json
        aws ecs register-task-definition --cli-input-json file://${{ github.workspace }}/task-definition.json
        def_arn=$( aws ecs describe-task-definition --task-definition $TASK_FAMILY --query taskDefinition.taskDefinitionArn --output text )
        aws ecs update-service --cluster $CLUSTER --service $SERVICE --task-definition $def_arn
        aws ecs wait services-stable --cluster $CLUSTER --services $SERVICE
