swagger: "2.0"
info:
  description: '<span class="govuk-body-m">You can use the interactive documentation to customise your API </br>response using the available query parameters. If you are registered and </br>logged in, you will be given a full response. Otherwise you will be given </br>an example response.</span><p><a class="govuk-link" href="/guidance/requirements/?section=Using the API">View developer documentation</a></p>'
  title: Timetables data API
  version: ""
basePath: "/api/v1"
paths:
  /dataset:
    get:
      tags:
        - Data set
      description: Returns all published datasets
      parameters:
        - in: query
          name: adminArea
          type: string
          description:
            Limit results to datasets with services that stop within the specified area(s).<br/>
            Comma separated list of admin areas defined by their AtcoAreaCode as specified in the NPTG area codes.

        - in: query
          name: endDateStart
          type: string
          format: date
          description:
            Limit results to data sets with services with end dates after this date.<br/>
            String formatted as YYYY-MM-DDTHH:MM:SS

        - in: query
          name: endDateEnd
          type: string
          format: date
          description:
            Limit results to data sets with services with end dates before this date.<br/>
            String formatted as YYYY-MM-DDTHH:MM:SS

        - in: query
          name: limit
          type: integer
          format: int32
          maximum: 100
          description: The maximum number of records to return
          default: 25

        - in: query
          name: modifiedDate
          type: string
          format: date
          description:
            Limit results to data sets that have been created/updated since the specified date.<br/>
            String formatted as YYYY-MM-DDTHH:MM:SS

        - in: query
          name: noc
          type: string
          description:
            Limit results to data sets published by an operator identified by the specified National Operator Code.<br/>
            Comma separated list of National Operator Codes

        - in: query
          name: offset
          type: integer
          format: int32
          maximum: 100
          description:
            Return results that match the query starting from the specified offset.<br/>
            e.g. &offset=10&limit=25 returns results from 11 to 36
          default: 0

        - in: query
          name: search
          type: string
          description: Return data sets where the data set name, data set description, organisation name, or admin area name contain the specified value

        - in: query
          name: status
          type: array
          items:
            type: string
            enum:
              - published
              - error
              - expired
              - inactive
          collectionFormat: multi
          description: Limit results to data sets with the specified status
            String, accepted values are published, error, expired

        - in: query
          name: startDateStart
          type: string
          format: date
          description:
            Limit results to data sets with services with start dates after this date.<br/>
            String formatted as YYYY-MM-DDTHH:MM:SS

        - in: query
          name: startDateEnd
          type: string
          format: date
          description:
            Limit results to data sets with services with start dates before this date.<br/>
            String formatted as YYYY-MM-DDTHH:MM:SS

      responses:
        200:
          description: Successfully retrieved all datasets
        400:
          description: Invalid data supplied

  /dataset/{datasetID}:
    get:
      tags:
        - Data set
      summary: Find dataset by ID
      description: Returns a single dataset
      parameters:
        - name: datasetID
          in: path
          description: ID of dataset to return
          required: true
          type: integer
          format: int64
      responses:
        "200":
          description: successful operation

        "400":
          description: Invalid ID supplied
        "404":
          description: Dataset not found
