name: pip-audit

on:
  workflow_dispatch:

defaults:
  run:
    working-directory: ./

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9  # change to your required version of Python

      - uses: pypa/gh-action-pip-audit@v1.0.6
        with:
          inputs: .