name: pytest

on:
 workflow_dispatch

defaults:
   run:
    working-directory: ./

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10.0"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run pytest
      run: | 
        pytest
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}

# name: pytest

# on:
#   # push:
#   #   branches:
#   #   - 'dev'
#   #   paths:
#   #   - version.txt
#   workflow_dispatch:

# defaults:
#   run:
#     working-directory: ./

# jobs:
#   build:

#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         python-version: ["3.7", "3.8", "3.9", "3.10"]

#     steps:    
#       - uses: actions/checkout@v3
#       - name: Set up Python ${{ matrix.python-version }}
#         uses: actions/setup-python@v4
#         with:
#           python-version: ${{ matrix.python-version }}

#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install flake8 pytest
#           if [ -f requirements.txt ]; then pip install -r requirements.txt; fi      
#           pip install Django
#           pip install django-environ
#           pip install python-dateutil
          
#       - name: Test with pytest
#         run: |
#           pip install pytest-django
#           pip install pytest
#           pip install pytest-cov
#           pytest ./