name: pytest

on:
 workflow_dispatch

defaults:
   run:
    working-directory: ./

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run pytest
      run: | 
        pytest
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        DJANGO_PARENT_HOST: ${{ secrets.DJANGO_PARENT_HOST }}
        CELERY_BROKER_URL: ${{ secrets.CELERY_BROKER_URL}}
        DJANGO_SETTINGS_MODULE: ${{ secrets.DJANGO_SETTINGS_MODULE}}
        CAVL_VALIDATION_URL: "https://api-sirivm-validate-cavl-staging.itoworld.com"
        CAVL_CONSUMER_URL: "https://api-consumer-cavl-staging.itoworld.com"
        CAVL_URL : "https://api-consumer-cavl-staging.itoworld.com"
        GOOGLE_ANALYTICS_KEY : ""
        AVL_LOWER_THRESHOLD : 0.45
        ITO_GTFS_AWS_ACCESS_KEY_ID : ${{ secrets.ITO_GTFS_AWS_ACCESS_KEY_ID}}
        ITO_GTFS_AWS_SECRET_ACCESS_KEY : ${{ secrets.ITO_GTFS_AWS_SECRET_ACCESS_KEY}}
        ITO_GTFS_AWS_REGION : "eu-west-2"
        TXC_SCHEMA_ZIP_URL : "http://www.transxchange.org.uk/schema/2.4/TransXChange_schema_2.4.zip"
        TXC_XSD_PATH : "TransXChange_general.xsd"
        NETEX_SCHEMA_ZIP_URL : "http://netex.uk/netex/schema/1.09c/NeTEx_Xml-v1.09c_2019.05.17.zip"
        NETEX_XSD_PATH: "xsd/NeTEx_publication.xsd"
        PTI_START_DATE: "2021-04-01"
        PTI_ENFORCED_DATE : "2021-08-02"
        PTI_PDF_URL : "https://pti.org.uk/system/files/files/TransXChange_UK_PTI_Profile_v1.1.A.pdf"
        MS_TENANT_ID : ${{ secrets.MS_TENANT_ID}}
        MS_LOGIN_URL : https://login.microsoftonline.com
        MS_SCOPE : "https://DVSAUK.onmicrosoft.com/{MS_CLIENT_ID}/.default"
        OTC_API_URL: "https://volapi.app.olcs.dvsacloud.uk/1.0/psv/busservice"
        OTC_API_KEY: ""
        GOV_NOTIFY_API_KEY : ${{ secrets.GOV_NOTIFY_API_KEY}}
        DQS_URL : https://api3-bods-staging.itoworld.com
        DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY}}
        REDIS_URL: redis://redis:6379/0
        DJANGO_AWS_STORAGE_BUCKET_NAME: "bodds-dev"
        DJANGO_AWS_SIRIVM_STORAGE_BUCKET_NAME: "bodds-dev-sirivm"
        DJANGO_DATA_SUBDOMAIN: "data"
        DJANGO_PUBLISH_SUBDOMAIN: "publish"
        DJANGO_ADMIN_SUBDOMAIN: "www"





# name: pytest

# on:
#   # push:
#   #   branches:
#   #   - 'dev'
#   #   paths:
#   #   - version.txt
#   workflow_dispatch:

# defaults:
#   run:
#     working-directory: ./

# jobs:
#   build:

#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         python-version: ["3.7", "3.8", "3.9", "3.10"]

#     steps:    
#       - uses: actions/checkout@v3
#       - name: Set up Python ${{ matrix.python-version }}
#         uses: actions/setup-python@v4
#         with:
#           python-version: ${{ matrix.python-version }}

#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install flake8 pytest
#           if [ -f requirements.txt ]; then pip install -r requirements.txt; fi      
#           pip install Django
#           pip install django-environ
#           pip install python-dateutil
          
#       - name: Test with pytest
#         run: |
#           pip install pytest-django
#           pip install pytest
#           pip install pytest-cov
#           pytest ./