on:
  workflow_dispatch:

name: 'unit_test_execution'

defaults:
  run:
    working-directory: ./transit_odp/fares

env:  
  ECR_REPOSITORY_NAME: ${{ secrets.ECR_REPOSITORY }}
  ENVIRONMENT_NAME: dev

jobs:

  unit_test_execute:
    name: 'unit_test_execution'
    runs-on: ubuntu-latest
    environment:
      name: dev
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - run:
        name: run tests
        command: |
          . venv/bin/activate
          mkdir test-results
          pytest --junitxml=test-results/junit.xml
    - store_test_results:
        path: test-results
