on:
  push:
    branches:
    - 'IGH-577-unit-test-execution'
    paths:
    - '.github/workflows/unit_test_execution.yml'
  workflow_dispatch:

name: 'unit_test_execution'

defaults:
  run:
    working-directory: ./transit_odp/fares

env:  
  ENGINE: django.contrib.gis.db.backends.postgis
  NAME: transit_odp
  USER: transit_odp
  PASSWORD: transit_odp
  HOST: transit_odp
  PORT: 5432
  

jobs:

  unit_test_execute:
    name: 'unit_test_execution'
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python 3.9.16
      uses: actions/setup-python@v3
      with:
        python-version: "3.9.16"

    - name: Install dependencies
      run: |
        cd ./../../
        pwd
        python -m pip install pytest
        python -m pip install django
        python -m pip install django_hosts
        python -m pip install pytest_django
        python -m pip install django-environ
        python -m pip install python-dateutil --upgrade

    - name: Run pytest
      run: |
        pwd
        pytest
